### ISSUE TITLE
Inject test pulses and read generated data

### ISSUE THREAD

**Issue by magruber** [SiLab-Bonn/tpx3-daq#16]
To inject test pulses and reading generated data some steps need to be completed:
- [ ]  Write the PCR and read it back for validation (see #13)
- [x]  Set the DACs related to the internal test pulses (VTP_coarse & VTP_fine)
- [x]  Write the general config and read it back
- [x]  Write to the test pulse registers (TP_number, TP_period and TP_phase) and read them back 
- [ ]  Set the CTPR and read it back for validation (see #10 and #14) 
- [x]  Open the shutter
- [ ]  Read the data sequentially (see #12) 
- [x]  Close the shutter
- [ ]  Receive the "Internal TestPulse Finished" packet (see #15)
